# rubocop-rails-omakase のデフォルト設定を読み込み
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  # プロジェクトで使う Ruby のバージョン
  TargetRubyVersion: 3.2

  # チェック対象外のファイル
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
