version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: hikaru  # ←仮
      POSTGRES_PASSWORD: hikaru_pass  # ←仮
      TZ: Asia/Tokyo
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: bash -c "bundle exec rails db:create db:migrate && bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/postgres  # ←仮
      TZ: Asia/Tokyo
    depends_on:
      - db

volumes:
  db-data:
