default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: db
  port: 5432
  database: hikaru_dev
  username: hikaru
  password: hikaru_pass

test:
  <<: *default
  host: db
  port: 5432
  database: hikaru_test
  username: hikaru
  password: hikaru_pass

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") %>
